language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "L+Qhj2kZqAqCF7RflVzyuxNw3CInUrm9iCk0FZj5oPYdw1bEECgYx9chvYeKjNf2yOTOeOAH32/XH0pcI4+flh6Z8DP5n8eMoxt7xdogAyaTVyTxHTuinmwz7I7aZWdhwO5GuthMrMmWH/9hjCj6e9MHY+zPFa2c5/Us4Rb3gAw="
    on:
      tags: true
      node_js: "io.js"
